/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppDialog: typeof import('./components/AppDialog.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    copy: typeof import('././components/AppDialog.vuepy.vue')['default']
    Dialog: typeof import('./components/Dialog.vue')['default']
    GuildInviteBtn: typeof import('./components/GuildInviteBtn.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MemoryUsageBar: typeof import('./components/MemoryUsageBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
