services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/root/data
    environment:
      - DATABASE_PATH=/root/data/${COMPOSE_PROJECT_NAME}.db
    depends_on:
      - frontend

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"

volumes:
  data:
